services:
    web:
        image: drzlobjul/22-50-web
        deploy:
            replicas: 5
        ports:
            - 8080:80
        volumes:
            - "/home/vagrant/test2-17.02/web:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: drzlobjul/22-50-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
           - db_root_password
secrets:
    db_root_password:
        external: true
networks:
    app-network:
